version: '3.9'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'cycles'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      #  When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. You can easily populate your mysql services by mounting a SQL dump into that directory and provide custom images with contributed data. SQL files will be imported by default to the database specified by the MYSQL_DATABASE variable.
  database-pg:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_USER: 'cycles'
      POSTGRES_PASSWORD: 'cycles'
      POSTGRES_DB: 'cycles'
    volumes:
      - ./scripts/cycle-functions-pg.sql:/docker-entrypoint-initdb.d/init.sql
